Add the discord link to all the pages footer
ApplETS/Site-Web-App-ETS pull request #37
Opened 2021-10-25 01:12 UTC by MysticFragilist

Addition of the discord icon in the image folder also.

2021-10-31 17:56 UTC, camillebrulotte requested changes

2021-10-31 17:56 UTC, camillebrulotte commented on contact.html
> +          <a href="https://discord.gg/83dHEzUUJ4">
Pourrais-tu générer le lien avec le compte du club ? :) On voit ton discord pendant 2/3 secondes sinon

2021-11-22 04:57 UTC, MysticFragilist commented on contact.html
> +          <a href="https://discord.gg/83dHEzUUJ4">
c'est fait!

2021-12-31 01:31 UTC, camillebrulotte approved these changes
lgtm :D

2022-01-03 02:53 UTC, merged